
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Diana
 */
public class SistemaEnfermedades extends javax.swing.JInternalFrame {

    /**
     * Creates new form SistemaEnfermedades
     */
    public SistemaEnfermedades() {
        initComponents();
        setTitle("Sistema de diagnostico de enfermedades");
        setResizable(false);
        this.setLocationRelativeTo(null);
        texto.setEditable(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 36)); // NOI18N
        jLabel1.setText("Diagnostico de Enfermedades");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel2.setText("Instrucciones:");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel3.setText("Para iniciar el Test debe de iniciar en el sistema,");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel4.setText(" dado click en Iniciar y responder a las serie de ");

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        jLabel5.setText("preguntas que se le presentan. ");

        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel6.setText("Intolerancia a la Lactosa, Cancer en el estomago, Cancer de Colon  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel3.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a, b = 0, c = 0;
        a = JOptionPane.showConfirmDialog(rootPane, "¿Presenta hichazon,distension abdominal ?", null, YES_NO_OPTION);

        if (a == 0) {
            lactosa();
        } else if (a == 1) {
            b = JOptionPane.showConfirmDialog(rootPane, "¿Presenta dificultad al tragar ?", null, YES_NO_OPTION);

        }

        if (b == 1) {
            estomago();
        } else if (c == 1) {
            c = JOptionPane.showConfirmDialog(rootPane, "¿Presenta estrechamiento de las haces ?", null, YES_NO_OPTION);

        }
        if (c == 1) {
            colon();
        }
        else if (c == 1){
            JOptionPane.showMessageDialog(rootPane, "¿Usted no presenta ninguno de estos sintomas?", null, YES_NO_OPTION);
            
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables

    private void lactosa() {
        int i,j,k,l,m,n;
        i=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta diarrea?", null, YES_NO_OPTION);
        j=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta gases?", null, YES_NO_OPTION);
        k=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta nauseas?", null, YES_NO_OPTION);
        l=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta dolor de abdomen?", null, YES_NO_OPTION);
        m=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta ruidos estomacales?", null, YES_NO_OPTION);
        n=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta vomitos?", null, YES_NO_OPTION);
        
        if ((i==0) && (j==0) && (k==0) && (l==0) && (m==0) && (n==0)){
            
            String dg= "---------------------------------------------------\n"
                    +  "--- Sistema Experto de Diagnostico de enfermedades \n"
                    +  "--- Ingenieria en Sistemas                         \n"
                    +  "---------------------------------------------------\n"
                    +  "- Diagnostico de enfermedades                      \n"
                    +  "--- Usted Presente Intolerancia a la Lactosa ------\n"
                    +  "----Debe presentarse con su medico de confianza----\n"
                    +  "----------------------------------------------------";
            
            texto.setText(dg);
        }
        else {
            lactosa();
        }
        
    }

    private void estomago() {
       
          int i,j,k,l,m,n,o,p,q,r;
        i=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta Nausea con Vomitos?", null, YES_NO_OPTION);
        j=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta Acides estomacal frecuentemente?", null, YES_NO_OPTION);
        k=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta dificultad al tragar?", null, YES_NO_OPTION);
        l=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta perdida de peso?", null, YES_NO_OPTION);
        m=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta perdida de apetito ?", null, YES_NO_OPTION);
        n=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta hichazon constante?", null, YES_NO_OPTION);
        o=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta heces con sangre?", null, YES_NO_OPTION);
        p=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta ojos o piel amarillos?", null, YES_NO_OPTION);
        q=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta fatiga excesiva?", null, YES_NO_OPTION);
        r=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta Dolor de estomago?", null, YES_NO_OPTION);
        
        
        if ((i==0) && (j==0) && (k==0) && (l==0) && (m==0) && (n==0) && (o==0)&& (p==0)
                && (q==0) && (r==0)){
            
            String dg= "---------------------------------------------------\n"
                    +  "--- Sistema Experto de Diagnostico de enfermedades \n"
                    +  "--- Ingenieria en Sistemas                         \n"
                    +  "---------------------------------------------------\n"
                    +  "- Diagnostico de enfermedades                      \n"
                    +  "--- Usted Presenta Cancer de Estomago--------------\n"
                    +  "----Debe presentarse con su medico de confianza----\n"
                    +  "----------------------------------------------------";
            
            texto.setText(dg);
        }
        else {
            estomago();
        }
              
        
        }

    private void colon() {
        
           
          int i,j,k,l,m,n,o;
        i=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta Diarrea?", null, YES_NO_OPTION);
        j=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta estrechamiento de las heces?", null, YES_NO_OPTION);
        k=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta sensasiones de ir al sanitario y no son aliviadas luego de evacuar?", null, YES_NO_OPTION);
        l=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta heces obscuras o con sangrado?", null, YES_NO_OPTION);
        m=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta calambres o dolor abdominal?", null, YES_NO_OPTION);
        n=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta debilidad o fatiga?", null, YES_NO_OPTION);
        o=JOptionPane.showConfirmDialog(rootPane, "¿Usted presenta perdida de peso?", null, YES_NO_OPTION);
        
        
        if ((i==0) && (j==0) && (k==0) && (l==0) && (m==0) && (n==0) && (o==0)
             ){
            
            String dg= "---------------------------------------------------\n"
                    +  "--- Sistema Experto de Diagnostico de enfermedades \n"
                    +  "--- Ingenieria en Sistemas                         \n"
                    +  "---------------------------------------------------\n"
                    +  "- Diagnostico de enfermedades                      \n"
                    +  "--- Usted Presenta Cancer de Colon-----------------\n"
                    +  "----Debe presentarse con su medico de confianza----\n"
                    +  "----------------------------------------------------";
            
            texto.setText(dg);
        }
        else {
            colon();
        }
        
    }

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class texto {

        public texto() {
        }
    }
}
